#!/bin/bash

echo "Installing prerequisites"
sudo apt-get install curl build-essential libncurses5-dev openssl libssl-dev fop xsltproc make

if[ ! -e ./kerl ]
then 
	echo "Use curl to get kerl"
	curl -O https://raw.githubusercontent.com/spawngrid/kerl/master/kerl
	chmod a+x kerl
fi

echo "Use kerl to get and build erland, using named a named build"
./kerl build R14B03 r14b03

sudo ./kerl install r14b03 erlang/r14b03

./erlang/r14b03/activate

#sudo apt-get install build-essential libc6-dev-i386

echo "Getting Riak source"
git clone https://github.com/basho/riak.git

echo "building Riak"
cd riak
git checkout 1.0.2-release 
make all
make devrel #compile examlpes
