#!/bin/bash

echo "Installing prerequisites"
sudo apt-get install curl build-essential libncurses5-dev openssl libssl-dev fop xsltproc make

echo "Use curl to get kerl"
curl -O https://raw.github.com/spawngrid/kerl/master/kerl

echo "Use kerl to get and build erland"
chmod a+x kerl
./kerl build R14B03 r14b03

sudo apt-get install build-essential libc6-dev-i386

echo "Getting Riak source"
git clone https://github.com/basho/riak.git

echo "building Riak"
cd riak
git checkout 1.0.2-release 
make rel #/all?
make devrel
